apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: giohnny/kube-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
            #get ip with kb get services
            #value: "10.104.50.113"
            #get namespaces with kb get namespaces
            # Use cluster namespaces service_name.namespace
              value: "auth-service.default"
              #value: "10.244.0.98"
            - name: TASKS_FOLDER
              value: tasks
