apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: giohnny/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
            #get ip with kb get services
            #value: "10.104.50.113"
            #get namespaces with kb get namespaces
            # Use cluster namespaces service_name.namespace
              value: "auth-service.default"
